#cloud-config
ssh_deletekeys: true
ssh_keys:
  rsa_private: |
    ${rsa-private}
  rsa_public: ${rsa-public}
  ecdsa_private: |
    ${ecdsa-private}
  ecdsa_public: ${ecdsa-public}

# By default, the fingerprints of the authorized keys for the users
# cloud-init adds are printed to the console. Setting
# no_ssh_fingerprints to true suppresses this output.
no_ssh_fingerprints: false

# By default, (most) ssh host keys are printed to the console. Setting
# emit_keys_to_console to false suppresses this output.
ssh:
  emit_keys_to_console: false

write_files:
# - path: /run/bootstrap/drupal-settings-update.sh
#   owner: root:root
#   permissions: "0755"
#   encoding: b64
#   content: £{drupal-settings-update}
- path: /run/bootstrap/sftp-config.sh
  owner: root:root
  permissions: "0755" 
  content: |

    # Installing the oci CLI
    yum install -y python36-oci-cli

    oci -v

    # Updates Drupal settings
    #/run/bootstrap/drupal-settings-update.sh

    # Restarts the Apache HTTPD
    #systemctl restart ssh

runcmd:
- [/run/bootstrap/sftp-config.sh]
#  - [rm, -rf, /run/bootstrap]