#cloud-config
groups:
- ${sftp-user-group}
users:
- default
- name: ${sftp-user-name}
  groups: ${sftp-user-group}
  lock_passwd: true
  no_create_home: true 
  no_user_group: true
  ssh_authorized_keys:
  - ${sftp-user-public-key}
  ssh_redirect_user: false
ssh_deletekeys: true
ssh_keys:
  rsa_private: |
    ${host-key-rsa-private}
  rsa_public: ${host-key-rsa-public}
  ecdsa_private: |
    ${host-key-ecdsa-private}
  ecdsa_public: ${host-key-ecdsa-public}
no_ssh_fingerprints: false
ssh:
  emit_keys_to_console: false

write_files:
- path: /run/bootstrap/sshd_config
  owner: root:root
  permissions: "0644"
  encoding: b64
  content: ${sshd_config}
- path: /run/bootstrap/bootstrap.sh
  owner: root:root
  permissions: "0755"
  encoding: b64 
  content: ${bootstrap-sh}
runcmd:
- [/run/bootstrap/bootstrap.sh]
#  - [rm, -rf, /run/bootstrap]